# frozen_string_literal: true

source "https://rubygems.org"

# 'aws-sdk-s3' is the official toolkit provided by Amazon to talk to S3.
gem 'aws-sdk-s3'

# 'pry' is a "Power User" debugger. It lets you pause your code while it's running
# to look around, check variables, and see what the computer is "thinking."
gem 'pry'

# 'nokogiri' is a powerful tool for reading and changing HTML/XML documents.
# You likely need this to parse data that comes back from AWS or web pages.
gem 'nokogiri'